### ISSUE TITLE
Files are not copied to Galaxy (sometimes)

### ISSUE THREAD

**Issue by mira-miracoli** [galaxyproject/pulsar#317] opened 2023-03-15 14:20 UTC
I observe mixed behaviour in my Pulsar endpoint:
 - everything works, the job is green, files are transferred, everything fine
 - the job is green, files are not transferred, but exist in the output dir
 - job is red, files are not transferred, but visible in the pulsar staging dir `working/out`
 - job is red, no files are produced, but when the command is run manually, it works and produces output files
 - job is green, no files are produced, but when the command is run manually, it works and produces output files

Currently I am unable to spot any pattern here or any reliable setting that works. I will try to observe changing parts around it more.
What adds up to it might be that some tools are not working as expected, e.g. ENAsearch is producing wrong output for xml.
And Galaxy Handlers are not picking up status messages sometimes, which is fixed by a handler restart

#### OS
RockyLinux 9.1
#### Pulsar
pulsar-app==0.14.13
#### Galaxy
23.0europe

**Comment by mvdbeek** [comment] 2023-03-15 15:29
0.14.13 is more than a year old. I would start by updating pulsar, then collect which tools produce errors in which category. We don't need data for all tools, a couple of examples should be sufficient. For each failing tool it'd then also be great to know the pulsar settings, the object store config as well as the relevant job destination parameters (extended metadata, remote metadata etc).

**Comment by mira-miracoli** [comment] 2023-03-16 07:36
Thank you @mvdbeek 
I will try to write everything down and update the VGCN Images to 0.14.15
> when that happens can you produce a stack dump with py-spy for the handler that is supposed to process messages  

Yes I can do that

**Comment by mtangaro** [comment] 2023-04-05 00:13
Hi all, I’m trying to find the working configuration of our pulsar endpoint with usegalaxy.eu.
Unfortunately, I’m also experiencing multiple behaviours, and I’m unable to identify the problems.

Run simple fastqc job.
- data staged, and processed. but not moved to “outputs” directory which is empty
- Pulsar logs: https://gist.githubusercontent.com/mtangaro/05aa3982d91992e122c6f4248afc7ed2/raw/49988b24f6b0cf85a51637819dc899d01d50b86c/gistfile1.txt
- Metadata directory output: https://gist.githubusercontent.com/mtangaro/1b286c26bfef77802b32e248d12036e5/raw/d9393039e3d7a40c94179d58cd07bef32d36ae47/gistfile1.txt
- working directory output:
```
$ ls working/
memory_statement.log  output.html  output.txt  Sc_INPUT_fastq  working
```
Fastqc was actually working fine, but after reinstalling the whole endpoint, no more. I can’t really find the problem here.

I see a different behaviour for mulled containers. For instance, a bowtie2 job, paired-end data, saccer3 reference data from history.
- data staged, but not processed. The singularity container is running:
```
root@vgcn-exec-node-1-usegalaxy-eu:~$ ps -aux | grep "singularity"
pulsar	117874  0.7  0.1 1630708 59600 ?   	Sl   01:40   0:01 singularity -s exec --cleanenv -B /data/share/staging/58490602:/data/share/staging/58490602 -B /data/share/staging/58490602/tool_files:/data/share/staging/58490602/tool_files:ro -B /data/share/staging/58490602/outputs:/data/share/staging/58490602/outputs -B /data/share/staging/58490602/working:/data/share/staging/58490602/working --home /data/share/staging/58490602/home:/data/share/staging/58490602/home docker://quay.io/biocontainers/mulled-v2-c742dccc9d8fabfcff2af0d8d6799dbc711366cf:e292900a5ccb65f879af393340758539ef14f345-0 /bin/bash /data/share/staging/58490602/tool_script.sh
root  	118153  0.0  0.0   6408  2228 pts/0	R+   01:43   0:00 grep --color=auto singularity
```
but, I think it is stuck at the signature stage. If I manually run as pulsar user the command.sh script, editing the singularity command to have outputs, I retrieve:
```
INFO:	Environment variable SINGULARITY_CACHEDIR is set, but APPTAINER_CACHEDIR is preferred
INFO:	Converting OCI blobs to SIF format
INFO:	Starting build...
Getting image source signatures
```
If I manually run the singularity command as pulsar user from command line, just to try, bowtie2 is run: https://gist.githubusercontent.com/mtangaro/3a478b5860f7e46f6ed487adbed11131/raw/e9081baf14c677f19e7219cbfa3474203c4627e5/gistfile1.txt

Finally, If I set the "job home directory as $HOME", the issue is there:
```
pulsar@vgcn-exec-node-1-usegalaxy-eu:/data/share/staging/58490602$ export HOME=/data/share/staging/58490602/home
pulsar@vgcn-exec-node-1-usegalaxy-eu:/data/share/staging/58490602$ echo $HOME
/data/share/staging/58490602/home
pulsar@vgcn-exec-node-1-usegalaxy-eu:/data/share/staging/58490602$ cd working/
pulsar@vgcn-exec-node-1-usegalaxy-eu:/data/share/staging/58490602/working$ singularity -v -s exec --cleanenv -B /data/share/staging/58490602:/data/share/staging/58490602 -B /data/share/staging/58490602/tool_files:/data/share/staging/58490602/tool_files:ro -B /data/share/staging/58490602/outputs:/data/share/staging/58490602/outputs -B /data/share/staging/58490602/working:/data/share/staging/58490602/working --home /data/share/staging/58490602/home:/data/share/staging/58490602/home docker://quay.io/biocontainers/mulled-v2-c742dccc9d8fabfcff2af0d8d6799dbc711366cf:e292900a5ccb65f879af393340758539ef14f345-0 /bin/bash /data/share/staging/58490602/tool_script.sh
INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
Getting image source signatures
```

Pulsar configuration details:

Pulsar Endpoint configuration on usegalaxy.eu: https://github.com/usegalaxy-eu/infrastructure-playbook/blob/7d0cfba99562e8ec5eb99c9939d71b9d91f00e43/files/galaxy/dynamic_rules/usegalaxy/destination_specifications.yaml#L737

Pulsar app,yml:
https://gist.githubusercontent.com/mtangaro/1ffc7b6f07ba255ac72398401cc69baf/raw/d8192e8b3a56aa60a169436e8c0743a935c56870/gistfile1.txt

local_env.sh: no configurations

server.ini: https://gist.githubusercontent.com/mtangaro/eefbcac22be194fb879e88e279a45a48/raw/00e9488fd81d8b443a16e54e58248d281d16660a/gistfile1.txt

OS: RockyLinux 9

Pulsar: 0.14.15

**Comment by mvdbeek** [comment] 2023-04-05 07:22
How did you both end up with 0.14.15 ? That version was only current for a couple of days and had a major bug

**Comment by mtangaro** [comment] 2023-04-05 07:26
> How did you both end up with 0.14.15 ? That version was only current for a single day and had a major bug

Because for EuroScienceGateway we are both using the same image with the same pulsar version. Do you recommend 
0.14.6 or 0.15.0dev1 (or both in two different endpoint)?

**Comment by mira-miracoli** [comment] 2023-04-05 07:27
I haven't seen any release notes, so I didn't know there was a bug.
Which version do you recommend? 0.14.15 or one of the dev versions?

**Comment by mvdbeek** [comment] 2023-04-05 07:32
Release notes are [here](https://pulsar.readthedocs.io/en/latest/history.html#id1) and [here](https://pypi.org/project/pulsar-app/), but even without the notes, why not go with the current version ? The pre-release version updates the k8s coexecution strategy to also work for tes for and adds a new option for amqp routes: https://github.com/galaxyproject/pulsar/compare/0.14.16...0.15.0.dev1#diff-e2de3cbc57ab9b097fca7d7c444c094ba3c1d4ee92b36d972d0d9d49669436cc

**Comment by hexylena** [comment] 2023-04-05 08:13
> and had a major bug

should we update the changelog then? it only notes "small regressions bugs"

**Comment by mtangaro** [comment] 2023-04-05 14:23
Hi Marius, again I'm very sorry for using the wrong Pulsar version. 
The update to 0.14.16 version solved the upload issue and fastqc is finally working (again).

On the contrary the issue with bowtie2 is still there, with the job still stuck.
The pulsar log: https://gist.githubusercontent.com/mtangaro/c5b24618beecbad0ab8be51169660d00/raw/e61408ca90a3e847d3d557019f65f2c0c0247528/gistfile1.txt
And the process in the exec node:
```
pulsar    140719  1.1  0.1 1562864 45920 ?       Sl   16:10   0:00 singularity -s exec --cleanenv -B /data/share/staging/58540489:/data/share/staging/58540489 -B /data/share/staging/58540489/tool_files:/data/share/staging/58540489/tool_files:ro -B /data/share/staging/58540489/outputs:/data/share/staging/58540489/outputs -B /data/share/staging/58540489/working:/data/share/staging/58540489/working --home /data/share/staging/58540489/home:/data/share/staging/58540489/home docker://quay.io/biocontainers/mulled-v2-c742dccc9d8fabfcff2af0d8d6799dbc711366cf:e292900a5ccb65f879af393340758539ef14f345-0 /bin/bash /data/share/staging/58540489/tool_script.sh
```
The singularity container is still not running:
```
$ singularity instance list
INSTANCE NAME    PID    IP    IMAGE
```
Do you have any idea?

**Comment by mvdbeek** [comment] 2023-04-05 14:56
I also see `WARNING: Cache disabled - cache location /opt/pulsar is not writable.` with the manual run, not sure which way you want to go with this, but the cache should be on a fast local disk.

**Comment by bgruening** [comment] 2023-04-06 16:01
Ok, a bit of progress. With the latest +dev1 version the `None` in the path are gone. A few tools are now working. More complicated tools like bowtie2 and star return in the Galaxy UI `Job 58583504's output dataset(s) could not be read`.

This above error is with ouputs_to_workingdir. If I disable to outputs_to_workingdir setting I get this traceback:

```
Apr 06 17:54:14 vgcn-central-manager-usegalaxy-eu.garr.cloud.pa pulsar[239718]: Traceback (most recent call last):
Apr 06 17:54:14 vgcn-central-manager-usegalaxy-eu.garr.cloud.pa pulsar[239718]:   File "/opt/pulsar/venv3/lib64/python3.9/site-packages/pulsar/client/staging/down.py", line 93, in __collect_working_directory_outputs
Apr 06 17:54:14 vgcn-central-manager-usegalaxy-eu.garr.cloud.pa pulsar[239718]:     self.output_files.remove(output_file)
Apr 06 17:54:14 vgcn-central-manager-usegalaxy-eu.garr.cloud.pa pulsar[239718]: ValueError: list.remove(x): x not in list
Apr 06 17:54:14 vgcn-central-manager-usegalaxy-eu.garr.cloud.pa pulsar[239718]: During handling of the above exception, another exception occurred:
Apr 06 17:54:14 vgcn-central-manager-usegalaxy-eu.garr.cloud.pa pulsar[239718]: Traceback (most recent call last):
Apr 06 17:54:14 vgcn-central-manager-usegalaxy-eu.garr.cloud.pa pulsar[239718]:   File "/opt/pulsar/venv3/lib64/python3.9/site-packages/pulsar/managers/stateful.py", line 223, in do_postprocess
Apr 06 17:54:14 vgcn-central-manager-usegalaxy-eu.garr.cloud.pa pulsar[239718]:     postprocess_success = postprocess(job_directory, self.__postprocess_action_executor)
Apr 06 17:54:14 vgcn-central-manager-usegalaxy-eu.garr.cloud.pa pulsar[239718]:   File "/opt/pulsar/venv3/lib64/python3.9/site-packages/pulsar/managers/staging/post.py", line 23, in postprocess
Apr 06 17:54:14 vgcn-central-manager-usegalaxy-eu.garr.cloud.pa pulsar[239718]:     collected = __collect_outputs(job_directory, staging_config, action_executor)
Apr 06 17:54:14 vgcn-central-manager-usegalaxy-eu.garr.cloud.pa pulsar[239718]:   File "/opt/pulsar/venv3/lib64/python3.9/site-packages/pulsar/managers/staging/post.py", line 38, in __collect_outputs
Apr 06 17:54:14 vgcn-central-manager-usegalaxy-eu.garr.cloud.pa pulsar[239718]:     collection_failure_exceptions = results_collector.collect()
Apr 06 17:54:14 vgcn-central-manager-usegalaxy-eu.garr.cloud.pa pulsar[239718]:   File "/opt/pulsar/venv3/lib64/python3.9/site-packages/pulsar/client/staging/down.py", line 69, in collect
Apr 06 17:54:14 vgcn-central-manager-usegalaxy-eu.garr.cloud.pa pulsar[239718]:     self.__collect_working_directory_outputs()
Apr 06 17:54:14 vgcn-central-manager-usegalaxy-eu.garr.cloud.pa pulsar[239718]:   File "/opt/pulsar/venv3/lib64/python3.9/site-packages/pulsar/client/staging/down.py", line 95, in __collect_working_directory_outputs
Apr 06 17:54:14 vgcn-central-manager-usegalaxy-eu.garr.cloud.pa pulsar[239718]:     raise Exception("Failed to remove {} from {}".format(output_file, self.output_files))
Apr 06 17:54:14 vgcn-central-manager-usegalaxy-eu.garr.cloud.pa pulsar[239718]: Exception: Failed to remove None from ['/data/dnb08/galaxy_db/files/1/9/5/dataset_1951953a-c2dc-42d9-ae6e-82ac5a4684e2.dat', '/data/dnb08/galaxy_db/files/a/8/d/dataset_a8dbe145-63a8-48d3-8106-4beeeb0721cc.dat', '/data/dnb08/galaxy_db/files/3/4/e/dataset_34e6f145-8543-4746-bf58-abc5f760a5e1.dat']

```

During debugging I found that we are not setting `--pwd` in Singularity, which I think we be good, to force a working dir. 


I can not prove it, but I have the feeling that handlers are forgetting pulsar jobs from time to time. I try to understand this, but what out for it if you debug pulsar.

**Comment by mvdbeek** [comment] 2023-04-06 16:09
> This above error is with ouputs_to_workingdir.

that is not a setting that makes sense or is compatible with pulsar, see https://github.com/galaxyproject/pulsar/issues/193#issuecomment-1106377936

> During debugging I found that we are not setting `--pwd` in Singularity, which I think we be good, to force a working dir.

that's not needed for .org and we are running pulsar with singularity (correct me if I'm wrong @natefoo)

I'll take a look at the traceback, it looks like something I already fixed in a different spot of the codebase. Do you know what tool this was ?

**Comment by bgruening** [comment] 2023-04-06 16:14
> This above error is with ouputs_to_workingdir.

that is not a setting that makes sense or is compatible with pulsar, see https://github.com/galaxyproject/pulsar/issues/193#issuecomment-1106377936

Yes, I know, but if this is part of our default destinations (non-pulsar settings) I think pulsar should ignore it. But it seems ti actually does something with it.

> During debugging I found that we are not setting `--pwd` in Singularity, which I think we be good, to force a working dir.

that's not needed for .org and we are running pulsar with singularity (correct me if I'm wrong @natefoo)

Its not needed, just a convenience for admins and more explicit. Ignore it, was just an observation.

I'll take a look at the traceback, it looks like something I already fixed in a different spot of the codebase. Do you know what tool this was ?

FASTQC and Star. Funnily, FASTQC works with `outputs_to_working_directory=true` and turns green. But crashes with `outputs_to_working_directory=false`

You have on EU under user preference an option where you can choose your destinations:

![grafik](https://user-images.githubusercontent.com/469983/230437200-29bf2a38-6c88-4e16-9a36-fb124c231ec0.png)

**Comment by bgruening** [comment] 2023-04-06 16:16
(sorry edited your comment instead of replying)

**Comment by mvdbeek** [comment] 2023-04-08 07:57
> But crashes with `outputs_to_working_directory=false`

that is probably fixed by https://github.com/galaxyproject/galaxy/pull/15918/commits/ff8835b75771a79922faa209cb65c2c192f015ad ... at least it was flagged in the framework tests

**Comment by bgruening** [comment] 2023-04-08 08:05
Thanks @mvdbeek 
I'm happy to test this on EU as soon as you think it's ready.

**Comment by bgruening** [comment] 2023-04-10 21:36
Thanks @mvdbeek! I have updated Galaxy to the latest 23.0 commit and the pulsar server to dev2.

Star fails with the `None` error again.

```
2678]] Failed to execute staging out file /data/share/staging/58682678/working/Log.final.out via FileAction[path=None,action_type=remote_transfer,url=https://usegalaxy.eu/_job_files?job_id=11ac94870d0bb33a2ff31a8386e3421c&job_key=b269333ccac1e9147600fa818dc8aa4a&path=None&file_type=output_workdir], retrying in 2.0 seconds.
Apr 10 23:24:31 vgcn-central-manager-usegalaxy-eu.garr.cloud.pa pulsar[464405]: Traceback (most recent call last):
Apr 10 23:24:31 vgcn-central-manager-usegalaxy-eu.garr.cloud.pa pulsar[464405]:   File "/opt/pulsar/venv3/lib64/python3.9/site-packages/pulsar/managers/util/retry.py", line 93, in _retry_over_time
Apr 10 23:24:31 vgcn-central-manager-usegalaxy-eu.garr.cloud.pa pulsar[464405]:     return fun(*args, **kwargs)
Apr 10 23:24:31 vgcn-central-manager-usegalaxy-eu.garr.cloud.pa pulsar[464405]:   File "/opt/pulsar/venv3/lib64/python3.9/site-packages/pulsar/managers/staging/post.py", line 82, in <lambda>
Apr 10 23:24:31 vgcn-central-manager-usegalaxy-eu.garr.cloud.pa pulsar[464405]:     self.action_executor.execute(lambda: action.write_from_path(pulsar_path), description)
Apr 10 23:24:31 vgcn-central-manager-usegalaxy-eu.garr.cloud.pa pulsar[464405]:   File "/opt/pulsar/venv3/lib64/python3.9/site-packages/pulsar/client/action_mapper.py", line 482, in write_from_path
Apr 10 23:24:31 vgcn-central-manager-usegalaxy-eu.garr.cloud.pa pulsar[464405]:     post_file(self.url, pulsar_path)
Apr 10 23:24:31 vgcn-central-manager-usegalaxy-eu.garr.cloud.pa pulsar[464405]:   File "/opt/pulsar/venv3/lib64/python3.9/site-packages/pulsar/client/transport/curl.py", line 77, in post_file
Apr 10 23:24:31 vgcn-central-manager-usegalaxy-eu.garr.cloud.pa pulsar[464405]:     raise Exception(message)
Apr 10 23:24:31 vgcn-central-manager-usegalaxy-eu.garr.cloud.pa pulsar[464405]: Exception: Failed to post_file properly for url https://usegalaxy.eu/_job_files?job_id=11ac94870d0bb33a2ff31a8386e3421c&job_key=b269333ccac1e9147600fa818dc8aa4a&path=None&file_type=output_workdir, remote server returned status code of 500.
Apr 10 23:24:36 vgcn-central-manager-usegalaxy-eu.garr.cloud.pa pulsar[464405]: 2023-04-10 23:24:36,852 INFO  [pulsar.managers.util.retry][[manager=production]-[action=postprocess]-[job=58682678]] Failed to execute staging out file /data/share/staging/58682678/working/Log.final.out via FileAction[path=None,action_type=remote_transfer,url=https://usegalaxy.eu/_job_files?job_id=11ac94870d0bb33a2ff31a8386e3421c&job_key=b269333ccac1e9147600fa818dc8aa4a&path=None&file_type=output_workdir], retrying in 4.0 seconds.
```
Fastqc fails similarly with:

```
Apr 10 23:28:34 vgcn-central-manager-usegalaxy-eu.garr.cloud.pa pulsar[464405]: 2023-04-10 23:28:34,416 INFO  [pulsar.managers.util.retry][[manager=production]-[action=postprocess]-[job=58682692]] Failed to execute staging out file /data/share/staging/58682692/working/output.html via FileAction[path=None,action_type=remote_transfer,url=https://usegalaxy.eu/_job_files?job_id=11ac94870d0bb33a1f919eeaac1d4c23&job_key=b269333ccac1e91404917e3d08c2ca32&path=None&file_type=output_workdir], retrying in 2.0 seconds.
Apr 10 23:28:34 vgcn-central-manager-usegalaxy-eu.garr.cloud.pa pulsar[464405]: Traceback (most recent call last):
Apr 10 23:28:34 vgcn-central-manager-usegalaxy-eu.garr.cloud.pa pulsar[464405]:   File "/opt/pulsar/venv3/lib64/python3.9/site-packages/pulsar/managers/util/retry.py", line 93, in _retry_over_time
Apr 10 23:28:34 vgcn-central-manager-usegalaxy-eu.garr.cloud.pa pulsar[464405]:     return fun(*args, **kwargs)
Apr 10 23:28:34 vgcn-central-manager-usegalaxy-eu.garr.cloud.pa pulsar[464405]:   File "/opt/pulsar/venv3/lib64/python3.9/site-packages/pulsar/managers/staging/post.py", line 82, in <lambda>
Apr 10 23:28:34 vgcn-central-manager-usegalaxy-eu.garr.cloud.pa pulsar[464405]:     self.action_executor.execute(lambda: action.write_from_path(pulsar_path), description)
Apr 10 23:28:34 vgcn-central-manager-usegalaxy-eu.garr.cloud.pa pulsar[464405]:   File "/opt/pulsar/venv3/lib64/python3.9/site-packages/pulsar/client/action_mapper.py", line 482, in write_from_path
Apr 10 23:28:34 vgcn-central-manager-usegalaxy-eu.garr.cloud.pa pulsar[464405]:     post_file(self.url, pulsar_path)
Apr 10 23:28:34 vgcn-central-manager-usegalaxy-eu.garr.cloud.pa pulsar[464405]:   File "/opt/pulsar/venv3/lib64/python3.9/site-packages/pulsar/client/transport/curl.py", line 77, in post_file
Apr 10 23:28:34 vgcn-central-manager-usegalaxy-eu.garr.cloud.pa pulsar[464405]:     raise Exception(message)
Apr 10 23:28:34 vgcn-central-manager-usegalaxy-eu.garr.cloud.pa pulsar[464405]: Exception: Failed to post_file properly for url https://usegalaxy.eu/_job_files?job_id=11ac94870d0bb33a1f919eeaac1d4c23&job_key=b269333ccac1e91404917e3d08c2ca32&path=None&file_type=output_workdir, remote server returned status code of 500.
``

**Comment by mvdbeek** [comment] 2023-04-11 09:22
it'd be amazing if we could hook up pulsar to sentry ... i wonder why we don't have a `path`

**Comment by bgruening** [comment] 2023-04-11 09:28
Is that a feature or deployment wish? ;)

**Comment by mvdbeek** [comment] 2023-04-11 11:02
hmm, I can't get it to fail ... which is good and bad 😆. That's still fastqc with https://github.com/usegalaxy-eu/infrastructure-playbook/blob/fc5d2f3438ed6edbc8f8d26e5b96056c1c3e3cd2/files/galaxy/dynamic_rules/usegalaxy/destination_specifications.yaml#L737 ?

**Comment by bgruening** [comment] 2023-04-11 11:22
The one above. With workingdir = false. You can choose that in your user preferences on EU

**Comment by mvdbeek** [comment] 2023-04-11 11:24
It actually all works for me, with or without `outputs_to_working_directory`, super weird. I'm gonna add the sentry integration, hoping the local variables will help us figure out what's going on.

**Comment by bgruening** [comment] 2023-04-11 17:51
Let me know if I can do anything to debug this further. As you know we have celery enabled and metadata_stradegy=extended.

**Comment by mvdbeek** [comment] 2023-04-11 17:52
I got access to one of the pulsar nodes, and I see it fail there. deploying some debugging now.

**Comment by mvdbeek** [comment] 2023-04-11 20:49
Could you try https://github.com/galaxyproject/galaxy/commit/fd80dde17346cd45d465326a7f2a52d358464692? It's possible that the way we build the JobIO instances we may have a reference to the global outputs_to_working_directory setting instead of the one specified in the job destination. ... if that was the problem though we

**Comment by bgruening** [comment] 2023-04-11 21:03
I started something similar before:

> Apr 11 23:01:56 sn06.galaxyproject.eu python[135946]: galaxy.jobs.runners WARNING 2023-04-11 23:01:56,878 [pN:handler_sn06_4,p:135946,tN:PulsarJobRunner.work_thread-1] BAG-log: /data/dnb08/galaxy_db/files/5/9/b/dataset_59b363e1-b397-4634-9bd1-c64c4a536d6b.dat
Apr 11 23:01:56 sn06.galaxyproject.eu python[135946]: galaxy.jobs.runners WARNING 2023-04-11 23:01:56,878 [pN:handler_sn06_4,p:135946,tN:PulsarJobRunner.work_thread-1] BAG-log: In outputs_to_woking_directory None
Apr 11 23:01:56 sn06.galaxyproject.eu python[135946]: galaxy.jobs.runners WARNING 2023-04-11 23:01:56,878 [pN:handler_sn06_4,p:135946,tN:PulsarJobRunner.work_thread-1] BAG-log: /data/dnb08/galaxy_db/files/6/9/a/dataset_69ad2920-743a-490d-a5cd-9cb897065b57.dat
Apr 11 23:01:56 sn06.galaxyproject.eu python[135946]: galaxy.jobs.runners WARNING 2023-04-11 23:01:56,879 [pN:handler_sn06_4,p:135946,tN:PulsarJobRunner.work_thread-1] BAG-log: In outputs_to_woking_directory None


![grafik](https://user-images.githubusercontent.com/469983/231287657-f29cbf8d-8429-47cf-9329-1d44cabc54e2.png)

Will run your patch next.

**Comment by bgruening** [comment] 2023-04-11 21:15
The `path` is always true.

**Comment by mvdbeek** [comment] 2023-04-11 21:26
`real_path` is always defined, but false_path is only being set up if `outputs_to_working_directory` is true. Looks like there is a mismatch somewhere in the life cycle of the job wrapper instance ... very weird. If you have the logs from https://github.com/galaxyproject/galaxy/commit/fd80dde17346cd45d465326a7f2a52d358464692 maybe we can figure this out based on the job destinations

**Comment by mvdbeek** [comment] 2023-04-12 07:36
OMG!!! `outputs_to_working_directory ` is a string ....

**Comment by mvdbeek** [comment] 2023-04-12 08:01
https://github.com/galaxyproject/galaxy/pull/15927 should fix this 🤞

**Comment by bgruening** [comment] 2023-04-12 21:25
I think we can close this. The majority of tools seem to work now and we can proceed I think.

Thanks a lot @mvdbeek for all your support!

**Closed by bgruening** 2023-04-12 21:25 UTC
Labels: confirmed bug
